### ISSUE TITLE
[BUG]: "cannot be enabled due to issues in required dependencies"

### ISSUE THREAD

**Issue by andresyuhnke** [RPG-Made-Simple/FVTT-ItemTags#10]
### Discord Username

andresyuhnke

### Browsers

Chrome, Edge, Native Foundry Client

### What Happened?

the checkbox to enable the module is greyed out. hovering over the checkbox I get the following error: "cannot be enabled due to issues in required dependencies"

running Foundry v11.315 DnD5e v2.4.1

### Reproduction Steps

```bash
attempt to enable module.
```

**Comment by ZotyDev** [comment]
Check if you have [🕷️ Debugger](https://foundryvtt.com/packages/debugger) and [🛠️ Tooblox](https://foundryvtt.com/packages/toolbox) installed and enabled.

**Comment by andresyuhnke** [comment]
Thanks Zoty, that seems to fix it. I didn't see that those were required dependencies.
